/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        heading: ['Manrope', 'system-ui', 'sans-serif'],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Manrope"],
        "headline-lg": ["Manrope"],
        "data-tabular": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Manrope"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-tabular": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      },
      spacing: {
        "unit": "4px",
        "container-margin": "24px",
        "gutter": "16px",
        "widget-padding": "20px",
        "table-row-height": "40px"
      },
      colors: {
        "primary-fixed": "#d2e4ff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "secondary": "#505f76",
        "surface-variant": "#e0e3e5",
        "inverse-surface": "#2d3133",
        "tertiary-fixed": "#c9e6ff",
        "on-tertiary-fixed-variant": "#004c6e",
        "tertiary-container": "#004f73",
        "surface-container-high": "#e6e8ea",
        "outline": "#727780",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#0b1c30",
        "on-primary": "#ffffff",
        "background": "#f7f9fb",
        "primary-container": "#0f4c81",
        "on-surface-variant": "#42474f",
        "on-tertiary-container": "#64c3ff",
        "surface": "#f7f9fb",
        "on-error-container": "#93000a",
        "on-background": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed-dim": "#a0c9ff",
        "tertiary": "#003752",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "on-primary-fixed-variant": "#07497d",
        "secondary-fixed": "#d3e4fe",
        "on-secondary-fixed-variant": "#38485d",
        "on-primary-fixed": "#001c37",
        "primary": "#00355f",
        "inverse-primary": "#a0c9ff",
        "tertiary-fixed-dim": "#89ceff",
        "surface-container-low": "#f2f4f6",
        "surface-tint": "#2d6197",
        "secondary-container": "#d0e1fb",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed": "#001e2f",
        "on-primary-container": "#8ebdf9",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container-highest": "#e0e3e5",
        "outline-variant": "#c2c7d1",
        "on-secondary-container": "#54647a",
        "surface-container": "#eceef0",
        "on-surface": "#191c1e",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        surface: {
          1: "hsl(var(--surface-1))",
          2: "hsl(var(--surface-2))",
          3: "hsl(var(--surface-3))",
        },
      },
      borderRadius: {
        lg: "0.5rem",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "0.75rem",
        full: "1rem"
      },
    },
  },
  plugins: [],
}
